services:
  clickhouse:
    build: ./clickhouse
    healthcheck:
      test: "wget -q -O - 'http://localhost:8123/?query=SELECT%201'"
      interval: 1m30s
      timeout: 15s
      retries: 3
      start_period: 1h
      start_interval: 30s
    volumes:
      # mount data dir for persistence, logs for debugging, and init scripts
      - ./data/:/var/lib/clickhouse/user_files/
      - ./clickhouse/container/data/:/var/lib/clickhouse/
      - ./clickhouse/container/logs/:/var/log/clickhouse-server/
      - ./clickhouse/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "8123:8123"
    networks:
      - citibike_network

  mapserver:
    extends:
      file: docker-compose.yml
      service: mapserver
    depends_on:
      - clickhouse

  map:
    extends:
      file: docker-compose.yml
      service: map

networks:
  citibike_network:
    driver: bridge
