services:
  map:
    build: ./map
    restart: always
    volumes:
      - ./map:/usr/app
    ports:
      - "3000:3000"
    networks:
      - citibike_network
    command: npm run dev

networks:
  citibike_network:
    driver: bridge
