services:
  clickhouse:
    build: ./clickhouse
    healthcheck:
      test: "wget -q -O - 'http://localhost:8123/?query=SELECT%201'"
      interval: 1m30s
      timeout: 15s
      retries: 3
      start_period: 1h
      start_interval: 30s
    volumes:
      # mount data dir for persistence, logs for debugging, and init scripts
      - ./data/:/var/lib/clickhouse/user_files/
      - ./clickhouse/container/data/:/var/lib/clickhouse/
      - ./clickhouse/container/logs/:/var/log/clickhouse-server/
      - ./clickhouse/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "8123:8123"
    networks:
      - citibike_network

  # Redis services for mocking out vercel KV
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - citibike_network

  serverless-redis-http:
    ports:
      - '8079:80'
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: 'redis://redis:6379'
    networks:
      - citibike_network

  map:
    extends:
      file: docker-compose.yml
      service: map

networks:
  citibike_network:
    driver: bridge
